// Genre mapping for artists in the music league
// This maps known artists to their primary genres

export const artistGenreMap: Record<string, string[]> = {
  // Indie Folk / Indie Rock
  "Bon Iver": ["Indie Folk", "Alternative"],
  "Fleet Foxes": ["Indie Folk", "Baroque Pop"],
  "The Strokes": ["Indie Rock", "Garage Rock"],
  "The War On Drugs": ["Indie Rock", "Heartland Rock"],
  "The War On Drugs, Lucius": ["Indie Rock", "Heartland Rock"],
  "Pit Pony": ["Punk Rock", "Indie Rock"],
  "José González": ["Indie Folk", "Singer-Songwriter"],
  "Ethel Cain": ["Indie", "Slowcore"],
  "CMAT": ["Country", "Indie Pop"],
  "Royel Otis": ["Indie Rock", "Psychedelic"],
  "Fontaines D.C.": ["Post-Punk", "Indie Rock"],
  "Wolf Alice": ["Indie Rock", "Alternative"],
  "NewDad": ["Indie Rock", "Shoegaze"],
  "Lucy Dacus": ["Indie Rock", "Singer-Songwriter"],
  "SPRINTS": ["Post-Punk", "Indie Rock"],
  "Caamp": ["Indie Folk", "Americana"],
  "Colony House": ["Indie Rock", "Alternative"],
  "Cliffords": ["Indie Rock", "Dream Pop"],
  "The Wran": ["Irish Trad", "Folk Punk"],
  "flipturn": ["Indie Rock", "Alternative"],
  "Suki Waterhouse": ["Indie Pop", "Dream Pop"],
  "Geese": ["Art Rock", "Indie Rock"],
  "Turnover": ["Indie Rock", "Dream Pop"],
  "Foals": ["Indie Rock", "Art Rock"],
  "Metronomy": ["Electronic", "Indie Pop"],
  "Mitski": ["Indie Rock", "Art Pop"],
  "Dominic Fike": ["Indie Pop", "Alternative"],
  "Alex Cameron": ["Synth-Pop", "Indie Pop"],
  "KAWALA": ["Indie Pop", "Folk Pop"],
  "yunè pinku": ["Electronic", "Art Pop"],
  "Cerebella": ["Electronic", "Industrial"],
  "Maggie Rogers": ["Indie Pop", "Folk Pop"],
  "Beach House": ["Dream Pop", "Shoegaze"],
  "DIIV": ["Shoegaze", "Dream Pop"],
  "Deftones": ["Alternative Metal", "Shoegaze"],
  "Arcade Fire": ["Indie Rock", "Art Rock"],
  "My Chemical Romance": ["Emo", "Alternative Rock"],
  "The Pretty Reckless": ["Hard Rock", "Alternative Rock"],
  "MGMT": ["Psychedelic Pop", "Indie Rock"],
  "Cocteau Twins": ["Dream Pop", "Shoegaze"],
  "Los Campesinos!": ["Indie Rock", "Indie Pop"],
  "Neutral Milk Hotel": ["Indie Folk", "Baroque Pop"],
  "The Shins": ["Indie Pop", "Indie Rock"],
  "Nilüfer Yanya, Boy Harsher": ["Indie Rock", "Darkwave"],
  "Parcels": ["Disco", "Synth-Pop"],
  "Djo": ["Synth-Pop", "Indie Rock"],
  "Dead Man's Bones": ["Indie Folk", "Baroque Pop"],
  "DOPE LEMON": ["Psychedelic Rock", "Indie"],
  "She & Him": ["Indie Pop", "Folk Pop"],
  "Florence + The Machine": ["Indie Pop", "Art Rock"],

  // Rock Classics
  "The Clash": ["Punk Rock", "Post-Punk"],
  "Rage Against The Machine": ["Rap Metal", "Alternative Rock"],
  "The Cure": ["Post-Punk", "Gothic Rock"],
  "Fleetwood Mac": ["Rock", "Soft Rock"],
  "Dire Straits": ["Rock", "Blues Rock"],
  "The Cars": ["New Wave", "Power Pop"],
  "Black Sabbath": ["Heavy Metal", "Rock"],
  "Blue Öyster Cult": ["Hard Rock", "Psychedelic Rock"],
  "Supertramp": ["Progressive Rock", "Soft Rock"],
  "Depeche Mode": ["Synth-Pop", "New Wave"],
  "Pink Floyd": ["Progressive Rock", "Psychedelic Rock"],
  "Simon & Garfunkel": ["Folk Rock", "Soft Rock"],
  "Billy Joel": ["Piano Rock", "Pop Rock"],
  "The White Stripes": ["Garage Rock", "Blues Rock"],
  "The Raconteurs": ["Rock", "Blues Rock"],
  "Muse": ["Alternative Rock", "Progressive Rock"],
  "Turnstile": ["Hardcore Punk", "Post-Hardcore"],
  "Pulp": ["Britpop", "Alternative Rock"],
  "Public Service Broadcasting": ["Electronic Rock", "Post-Rock"],
  "Blur": ["Britpop", "Alternative Rock"],
  "Tame Impala": ["Psychedelic Rock", "Indie Rock"],
  "Queens of the Stone Age": ["Hard Rock", "Alternative Rock"],
  "Mogwai": ["Post-Rock", "Ambient"],
  "Guns N' Roses": ["Hard Rock", "Rock"],
  "Red Hot Chili Peppers": ["Alternative Rock", "Funk Rock"],
  "Rammstein": ["Industrial Metal", "Heavy Metal"],
  "Sum 41": ["Pop Punk", "Punk Rock"],
  "Paramore": ["Pop Punk", "Alternative Rock"],
  "Thirty Seconds To Mars": ["Alternative Rock", "Electronic Rock"],
  "Derek & The Dominos": ["Blues Rock", "Classic Rock"],
  "Omega": ["Progressive Rock", "Classic Rock"],
  "OK Go": ["Indie Rock", "Power Pop"],
  "Coldplay": ["Indie Rock", "Alternative Rock"],
  "Limp Bizkit": ["Nu Metal", "Rap Rock"],
  "Disturbed": ["Nu Metal", "Hard Rock"],
  "Tenacious D": ["Comedy Rock", "Hard Rock"],
  "Gorillaz": ["Alternative Rock", "Electronic"],
  "Gorillaz, De La Soul": ["Alternative Rock", "Hip-Hop"],
  "David Bowie": ["Art Rock", "Glam Rock"],
  "a-ha": ["Synth-Pop", "New Wave"],
  "Blondie": ["New Wave", "Pop"],
  "Headache": ["Experimental", "Electronic"],
  "The The": ["Post-Punk", "Alternative Rock"],
  "Aphrodite's Child": ["Progressive Rock", "Psychedelic"],
  "Molchat Doma": ["Post-Punk", "Synth-Pop"],
  "KALEO": ["Blues Rock", "Indie Rock"],
  "Parra for Cuva, Anna Naklab": ["Electronic", "Indie Pop"],
  "Tobtok, River": ["Electronic", "Dance Pop"],
  "Bob Marley & The Wailers, LVNDSCAPE, Bolier": ["Reggae", "Electronic"],
  "Flume, kai": ["Electronic", "Future Bass"],
  "Max Cooper, Rob Clouth": ["Electronic", "Ambient"],
  "The Bloody Beetroots, Mr. Talkbox": ["Electronic", "Funk"],
  "Ween": ["Alternative Rock", "Indie Rock"],

  // Hip-Hop/Rap
  "Eminem, Dido": ["Hip-Hop", "Rap"],
  "Kendrick Lamar": ["Hip-Hop", "Conscious Rap"],
  "JAŸ-Z": ["Hip-Hop", "Rap"],
  "JAŸ-Z, Kanye West": ["Hip-Hop", "Rap"],
  "Nas & Damian \"Jr. Gong\" Marley": ["Hip-Hop", "Reggae"],
  "Doechii": ["Hip-Hop", "Rap"],
  "Kanye West": ["Hip-Hop", "Art Pop"],
  "Kanye West, Pusha T": ["Hip-Hop", "Rap"],
  "Ms. Lauryn Hill": ["R&B", "Hip-Hop"],
  "Madvillain, Madlib, MF DOOM": ["Hip-Hop", "Abstract Hip-Hop"],
  "B.o.B, Eminem, Hayley Williams": ["Hip-Hop", "Pop Rap"],
  "Childish Gambino": ["Hip-Hop", "R&B"],
  "Wretch 32, Avelino": ["UK Hip-Hop", "Grime"],
  "The Pharcyde": ["Hip-Hop", "Jazz Rap"],
  "Stan Rogers": ["Folk", "Maritime"],
  "Lil Wayne": ["Hip-Hop", "Rap"],
  "Soulja Boy, Sammie": ["Hip-Hop", "Crunk"],
  "Kevin Rudolf, Lil Wayne": ["Pop Rock", "Hip-Hop"],
  "B.o.B": ["Hip-Hop", "Pop Rap"],

  // Electronic/Dance
  "Instupendo": ["Electronic", "Downtempo"],
  "Nia Archives": ["Jungle", "Drum and Bass"],
  "The Avalanches": ["Plunderphonics", "Electronic"],
  "Hot Chip": ["Electronic", "Synth-Pop"],
  "Daft Punk": ["Electronic", "House"],
  "PinkPantheress": ["UK Garage", "Dance Pop"],
  "100 gecs, Laura Les, Dylan Brady": ["Hyperpop", "Electronic"],
  "Four Tet": ["Electronic", "IDM"],
  "Caribou": ["Electronic", "Psychedelic"],
  "Basshunter, DJ Mental Theos Bazzheadz": ["Eurodance", "Trance"],
  "Alice Deejay": ["Trance", "Eurodance"],
  "Scooter": ["Happy Hardcore", "Techno"],
  "Special D.": ["Hands Up", "Eurodance"],
  "SOPHIE": ["Hyperpop", "Electronic"],
  "Two Shell": ["Electronic", "UK Bass"],
  "Ninajirachi": ["Electronic", "Hyperpop"],
  "nimino": ["Electronic", "Deep House"],
  "mischluft": ["Electronic", "House"],
  "Jax Jones, D.O.D, Ina Wroldsen, The Blackout Crew": ["Dance", "Electronic"],
  "GFOTY": ["Electronic", "Hyperpop"],
  "Getdown Services": ["Punk", "Electronic"],
  "T2": ["UK Garage", "Bassline"],
  "UFOs, Braxe + Falcon, Phoenix, Alan Braxe, DJ Falcon": ["Electronic", "House"],
  "Torren Foot, Azealia Banks": ["Electronic", "Hip-Hop"],
  "Fatima Yamaha": ["Electronic", "House"],
  "Touch Sensitive": ["Disco", "Electronic"],
  "Maribou State, Andreya Triana": ["Electronic", "Indie"],
  "Miracle Musical": ["Psychedelic Pop", "Art Rock"],
  "Jamie xx, MC Moose": ["Electronic", "UK Garage"],
  "MOTHERMARY, HERO": ["Synth-Pop", "Darkwave"],
  "Crozet": ["Electronic", "Chillwave"],

  // Pop
  "Taylor Swift": ["Pop", "Country Pop"],
  "Scissor Sisters": ["Pop", "Disco"],
  "Black Eyed Peas, The World": ["Pop", "Hip-Hop"],
  "Black Eyed Peas": ["Pop", "Hip-Hop"],
  "Lady Gaga": ["Pop", "Dance Pop"],
  "ABBA": ["Pop", "Disco"],
  "Kylie Minogue": ["Pop", "Dance Pop"],
  "Madonna": ["Pop", "Dance"],
  "Robyn": ["Pop", "Electronic"],
  "Britney Spears": ["Pop", "Dance Pop"],
  "Charli xcx": ["Pop", "Hyperpop"],
  "Ashnikko": ["Pop", "Hyperpop"],
  "Ariana Grande": ["Pop", "R&B"],
  "Addison Rae": ["Pop", "Dance Pop"],
  "Kim Petras": ["Pop", "Dance Pop"],
  "Lana Del Rey": ["Dream Pop", "Indie Pop"],
  "Kelis": ["R&B", "Pop"],
  "Whitney Houston": ["Pop", "R&B"],
  "Owl City": ["Synth-Pop", "Electronic"],
  "Hellogoodbye": ["Pop Punk", "Synth-Pop"],
  "Agnes": ["Pop", "Dance Pop"],
  "Toni Moralez": ["Electronic", "Dance"],
  "Timbaland, Keri Hilson, D.O.E.": ["Hip-Hop", "R&B"],
  "Zazie's Uh Flower": ["Novelty", "Children's"],
  "Maggie Reilly": ["Pop", "New Age"],
  "Gabrielle Aplin": ["Folk Pop", "Indie Pop"],

  // Jazz/Soul/R&B
  "Ella Fitzgerald, Louis Jordan": ["Jazz", "Vocal Jazz"],
  "Sylvester": ["Disco", "Soul"],
  "Funkadelic": ["Funk", "Psychedelic Soul"],
  "Christy Essien Igbokwe": ["Afrobeat", "Funk"],
  "Thundercat": ["Jazz Fusion", "Funk"],
  "Solange": ["R&B", "Neo-Soul"],
  "Bill Withers": ["Soul", "R&B"],
  "The Isley Brothers": ["Soul", "R&B"],
  "Labi Siffre": ["Soul", "Folk"],
  "Breakwater": ["Funk", "Soul"],
  "Rick James": ["Funk", "R&B"],
  "Ronnie Foster": ["Jazz", "Soul Jazz"],
  "Dionne Warwick": ["Soul", "Pop"],
  "Edwin Birdsong": ["Funk", "Disco"],
  "Diana Ross": ["Soul", "Disco"],
  "Joji": ["R&B", "Lo-fi"],
  "Amii Stewart": ["Disco", "Soul"],
  "The Gene Dudley Group": ["Disco", "Funk"],
  "Blood Orange, Tariq Al-Sabir, Caroline Polachek, Daniel Caesar, The Durutti Column": ["R&B", "Art Pop"],
  "Mulatu Astatke": ["Ethio-Jazz", "Jazz"],
  "Frank Sinatra": ["Jazz", "Vocal Jazz"],
  "The Ink Spots": ["Jazz", "Vocal Jazz"],

  // Reggae/Ska
  "Toots & The Maytals": ["Reggae", "Ska"],
  "Chaka Demus & Pliers": ["Reggae", "Dancehall"],
  "Big Mountain": ["Reggae", "Reggae Pop"],
  "Inner Circle": ["Reggae", "Reggae Pop"],
  "Aswad": ["Reggae", "Dub"],
  "Madness": ["Ska", "New Wave"],
  "KARAMUSHI, SUPER FRIENDS": ["Reggae", "Japanese"],
  "M-Beat, General Levy": ["Jungle", "Ragga"],
  "Cutty Ranks": ["Dancehall", "Reggae"],
  "UB40": ["Reggae", "Pop Reggae"],

  // Folk/Singer-Songwriter
  "Joni Mitchell": ["Folk", "Singer-Songwriter"],
  "Johnny Cash": ["Country", "Folk"],
  "Fountains Of Wayne": ["Power Pop", "Pop Rock"],
  "Jesse Sykes & The Sweet Hereafter": ["Alt-Country", "Folk Rock"],
  "Kate Nash": ["Indie Pop", "Singer-Songwriter"],
  "The Chieftains, Sinéad O'Connor": ["Irish Trad", "Celtic"],
  "Leonard Cohen": ["Folk", "Singer-Songwriter"],
  "Hozier": ["Folk Rock", "Soul"],
  "Lucy Dacus, Hozier": ["Indie Rock", "Folk Rock"],
  "The Mary Wallopers": ["Irish Trad", "Folk Punk"],
  "Bog Bodies": ["Irish Trad", "Folk Metal"],
  "Eadaoin": ["Irish Trad", "Folk"],
  "TPM": ["Irish Trad", "Folk Punk"],
  "Headmix Collective": ["Irish Trad", "Electronic"],
  "Yusuf / Cat Stevens": ["Folk", "Singer-Songwriter"],
  "Gordon Lightfoot": ["Folk", "Country Rock"],
  "Ólafur Arnalds, Talos, Niamh Regan, Ye Vagabonds": ["Neoclassical", "Folk"],
  "Alessi Brothers": ["Soft Rock", "Folk Pop"],
  "The Alessi Brothers": ["Soft Rock", "Folk Pop"],
  "Joram Feitsma": ["Neoclassical", "Ambient"],

  // World/International
  "Caetano Veloso": ["MPB", "Tropicália"],
  "Andrés Calamaro": ["Rock en Español", "Rock"],
  "Taeko Onuki": ["City Pop", "Jazz Pop"],
  "Howard Shore": ["Soundtrack", "Orchestral"],
  "Al Massrieen": ["Egyptian Pop", "Funk"],
  "Monomono": ["Afrobeat", "Funk"],
  "Hugh Masekela": ["Jazz", "Afrobeat"],
  "William Onyeabor": ["Synth Funk", "Afrobeat"],
  "Kiki Gyan": ["Disco", "Afrobeat"],
  "Ebo Taylor": ["Highlife", "Afrobeat"],
  "Surchoc": ["Zouglou", "African Pop"],
  "Sauti Sol": ["Afropop", "R&B"],
  "Chicco": ["Bubblegum", "South African"],
  "Fela Kuti": ["Afrobeat", "Jazz Funk"],
  "CKay": ["Afrobeats", "R&B"],
  "La Femme, Marlon Magnée, Saxa Goth": ["French Pop", "Psychedelic"],
  "Kazdoura": ["Arabic Rock", "Alternative"],
  "D.A.N.": ["Electronic", "Indie"],
  "Sigur Rós": ["Post-Rock", "Ambient"],
  "Alisha Chinai, Vijay Benedict": ["Bollywood", "Disco"],
  "Nada": ["Italian Pop", "Rock"],
  "Billo's Caracas Boys": ["Tropical", "Latin"],
  "Plastic Bertrand": ["Punk Rock", "New Wave"],
  "Zohra": ["Arabic Pop", "Disco"],
  "Hermanos Gutiérrez": ["Latin", "Instrumental Rock"],
  "Boney M.": ["Disco", "Euro Pop"],

  // Post-Rock / Ambient / Neoclassical
  "Mogwai": ["Post-Rock", "Ambient"],

  // Irish Artists
  "The Coronas": ["Indie Rock", "Irish Rock"],
  "The Cranberries": ["Alternative Rock", "Dream Pop"],
  "The Thrills": ["Indie Rock", "Indie Pop"],
  "my bloody valentine": ["Shoegaze", "Dream Pop"],
  "Two Door Cinema Club": ["Indie Rock", "New Wave"],
  "Pillow Queens": ["Indie Rock", "Post-Punk"],
  "The Stunning": ["Indie Rock", "Irish Rock"],
  "Little Green Cars": ["Folk Rock", "Indie Pop"],
  "Republic Of Loose": ["Indie Rock", "Funk Rock"],
  "Paddy Casey": ["Folk Rock", "Singer-Songwriter"],
  "Kean Kavanagh": ["Indie", "Irish"],
  "The Clockworks": ["Post-Punk", "Indie Rock"],
  "Morgana": ["Synth-Pop", "Indie Pop"],

  // Misc/Novelty
  "Crystal Swing": ["Country", "Novelty"],
  "William Shatner": ["Spoken Word", "Novelty"],
  "Mrs. Miller": ["Novelty", "Pop"],
  "Mambo Kurt": ["Novelty", "Covers"],
  "Gene Simmons": ["Hard Rock", "Covers"],
  "Monty Python": ["Comedy", "Novelty"],
  "Easy Going": ["Disco", "Eurodance"],
  "Danny Kaye, The Andrews Sisters, Vic Schoen & His Orchestra": ["Novelty", "Jazz"],
  "DJ Eugene McCauley, UTV": ["Novelty", "Comedy"],
  "Vanilla Ice": ["Hip-Hop", "Pop Rap"],
  "John Travolta, Olivia Newton-John": ["Pop", "Soundtrack"],
  "Gary Glitter": ["Glam Rock", "Rock"],
  "Eddie Murphy": ["R&B", "Novelty"],
  "Diddy - Dirty Money, Skylar Grey": ["Hip-Hop", "R&B"],
  "Robin Thicke, T.I., Pharrell Williams": ["R&B", "Pop"],
  "Amy Winehouse": ["Soul", "R&B"],
  "Justin Bieber": ["Pop", "R&B"],
  "Chris Brown": ["R&B", "Pop"],
  "Azealia Banks, Lazy Jay": ["Hip-Hop", "Electronic"],
  "Michael Jackson": ["Pop", "R&B"],
  "Ariel Pink": ["Lo-fi", "Psychedelic Pop"],
  "Prince": ["Pop", "Funk"],

  // Emerging / Small Irish / Other
  "Eve Appleton Band": ["Indie Rock", "Singer-Songwriter"],
  "Banshee": ["Indie Rock", "Post-Punk"],
  "Parlor Snakes": ["Indie Rock", "Post-Punk"],
  "HiTech": ["Electronic", "Grime"],
  "Melenas": ["Indie Pop", "Psychedelic"],
  "the north": ["Indie Rock", "Alternative"],
  "New Madrid": ["Indie Rock", "Alternative"],
  "Gretel": ["Indie Pop", "Singer-Songwriter"],
  "SILK": ["Electronic", "Dance"],
  "Teddybears, Iggy Pop": ["Electronic Rock", "Punk Rock"],
  "KAWALA": ["Indie Pop", "Folk Pop"],

  // More indie/alternative
  "Lana Del Rey": ["Dream Pop", "Indie Pop"],
  "Miracle Musical": ["Psychedelic Pop", "Art Rock"],
  "Circuladó": ["MPB", "Tropicália"],
  "Ween": ["Alternative Rock", "Indie Rock"],
  "The Weeknd": ["R&B", "Synth-Pop"],
  "Childish Gambino": ["Hip-Hop", "R&B"],
  "Thirty Seconds To Mars": ["Alternative Rock", "Electronic Rock"],
  "OK Go": ["Indie Rock", "Power Pop"],
  "Coldplay": ["Indie Rock", "Alternative Rock"],
  "KALEO": ["Blues Rock", "Indie Rock"],
  "Take That": ["Pop", "Dance Pop"],
};

// Fallback genre detection based on keywords/patterns
export function inferGenreFromArtist(artist: string): string[] {
  const lowerArtist = artist.toLowerCase();
  
  // Check direct mapping first
  if (artistGenreMap[artist]) {
    return artistGenreMap[artist];
  }
  
  // Try partial matches (check if the artist contains a mapped name or vice versa)
  for (const [mappedArtist, genres] of Object.entries(artistGenreMap)) {
    // Check for substring matches (handles "feat." and collaborations)
    if (lowerArtist.includes(mappedArtist.toLowerCase()) || 
        mappedArtist.toLowerCase().includes(lowerArtist)) {
      return genres;
    }
  }
  
  // Check for artist appearing in collaborations (e.g., "Artist1, Artist2")
  const artistParts = artist.split(/[,&]/).map(p => p.trim());
  for (const part of artistParts) {
    if (artistGenreMap[part]) {
      return artistGenreMap[part];
    }
    // Also check partial matches for each part
    for (const [mappedArtist, genres] of Object.entries(artistGenreMap)) {
      if (part.toLowerCase().includes(mappedArtist.toLowerCase()) || 
          mappedArtist.toLowerCase().includes(part.toLowerCase())) {
        return genres;
      }
    }
  }
  
  // Keyword-based inference
  if (lowerArtist.includes("dj") || lowerArtist.includes("remix")) {
    return ["Electronic", "Dance"];
  }
  if (lowerArtist.includes("jazz") || lowerArtist.includes("quartet")) {
    return ["Jazz"];
  }
  if (lowerArtist.includes("orchestra") || lowerArtist.includes("symphony")) {
    return ["Classical", "Orchestral"];
  }
  if (lowerArtist.includes("mc ") || lowerArtist.includes(" mc")) {
    return ["Hip-Hop", "Rap"];
  }
  
  return ["Other"];
}

export const genreColors: Record<string, string> = {
  // Primary genres
  "Indie Rock": "bg-indigo-500/20 text-indigo-400 border-indigo-500/30",
  "Indie Folk": "bg-amber-500/20 text-amber-400 border-amber-500/30",
  "Indie Pop": "bg-violet-500/20 text-violet-400 border-violet-500/30",
  "Indie": "bg-purple-500/20 text-purple-400 border-purple-500/30",
  "Alternative": "bg-purple-500/20 text-purple-400 border-purple-500/30",
  "Rock": "bg-red-500/20 text-red-400 border-red-500/30",
  "Hip-Hop": "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  "Rap": "bg-orange-500/20 text-orange-400 border-orange-500/30",
  "Electronic": "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
  "Pop": "bg-pink-500/20 text-pink-400 border-pink-500/30",
  "Jazz": "bg-blue-500/20 text-blue-400 border-blue-500/30",
  "Soul": "bg-rose-500/20 text-rose-400 border-rose-500/30",
  "R&B": "bg-fuchsia-500/20 text-fuchsia-400 border-fuchsia-500/30",
  "Reggae": "bg-green-500/20 text-green-400 border-green-500/30",
  "Folk": "bg-lime-500/20 text-lime-400 border-lime-500/30",
  "Country": "bg-amber-600/20 text-amber-500 border-amber-600/30",
  "Punk Rock": "bg-red-600/20 text-red-500 border-red-600/30",
  "Post-Punk": "bg-slate-500/20 text-slate-400 border-slate-500/30",
  "Disco": "bg-violet-500/20 text-violet-400 border-violet-500/30",
  "Funk": "bg-orange-600/20 text-orange-500 border-orange-600/30",
  "New Wave": "bg-teal-500/20 text-teal-400 border-teal-500/30",
  "Synth-Pop": "bg-sky-500/20 text-sky-400 border-sky-500/30",
  "Heavy Metal": "bg-zinc-500/20 text-zinc-400 border-zinc-500/30",
  "Progressive Rock": "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
  "Soundtrack": "bg-stone-500/20 text-stone-400 border-stone-500/30",
  "Dream Pop": "bg-indigo-400/20 text-indigo-300 border-indigo-400/30",
  "Shoegaze": "bg-purple-400/20 text-purple-300 border-purple-400/30",
  "Afrobeat": "bg-yellow-600/20 text-yellow-500 border-yellow-600/30",
  "Irish Trad": "bg-green-600/20 text-green-500 border-green-600/30",
  "UK Garage": "bg-blue-600/20 text-blue-500 border-blue-600/30",
  "Hyperpop": "bg-pink-400/20 text-pink-300 border-pink-400/30",
  "Dance Pop": "bg-pink-600/20 text-pink-500 border-pink-600/30",
  "Britpop": "bg-red-400/20 text-red-300 border-red-400/30",
  "Art Rock": "bg-purple-600/20 text-purple-500 border-purple-600/30",
  "Post-Rock": "bg-slate-400/20 text-slate-300 border-slate-400/30",
  "Downtempo": "bg-cyan-600/20 text-cyan-500 border-cyan-600/30",
  "Darkwave": "bg-slate-700/20 text-slate-400 border-slate-700/30",
  "Neoclassical": "bg-stone-400/20 text-stone-300 border-stone-400/30",
  "Chillwave": "bg-teal-400/20 text-teal-300 border-teal-400/30",
  "IDM": "bg-cyan-700/20 text-cyan-500 border-cyan-700/30",
  "Ambient": "bg-sky-400/20 text-sky-300 border-sky-400/30",
  "Future Bass": "bg-blue-400/20 text-blue-300 border-blue-400/30",
  "UK Hip-Hop": "bg-yellow-600/20 text-yellow-500 border-yellow-600/30",
  "Grime": "bg-orange-700/20 text-orange-500 border-orange-700/30",
  "Afrobeats": "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  "Afropop": "bg-yellow-400/20 text-yellow-300 border-yellow-400/30",
  "MPB": "bg-lime-600/20 text-lime-500 border-lime-600/30",
  "Tropicália": "bg-lime-500/20 text-lime-400 border-lime-500/30",
  "City Pop": "bg-pink-300/20 text-pink-200 border-pink-300/30",
  "Latin": "bg-orange-500/20 text-orange-400 border-orange-500/30",
  "Eurodance": "bg-sky-600/20 text-sky-500 border-sky-600/30",
  "Trance": "bg-blue-500/20 text-blue-400 border-blue-500/30",
  "Dancehall": "bg-green-700/20 text-green-500 border-green-700/30",
  "Ska": "bg-green-400/20 text-green-300 border-green-400/30",
  "Jungle": "bg-green-800/20 text-green-600 border-green-800/30",
  "Drum and Bass": "bg-cyan-800/20 text-cyan-600 border-cyan-800/30",
  "Plunderphonics": "bg-gray-500/20 text-gray-400 border-gray-500/30",
  "House": "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
  "Deep House": "bg-blue-700/20 text-blue-500 border-blue-700/30",
  "Garage Rock": "bg-red-700/20 text-red-500 border-red-700/30",
  "Blues Rock": "bg-blue-800/20 text-blue-600 border-blue-800/30",
  "Hard Rock": "bg-red-800/20 text-red-600 border-red-800/30",
  "Jazz Fusion": "bg-blue-600/20 text-blue-500 border-blue-600/30",
  "Neo-Soul": "bg-rose-600/20 text-rose-500 border-rose-600/30",
  "Lo-fi": "bg-amber-400/20 text-amber-300 border-amber-400/30",
  "Art Pop": "bg-fuchsia-500/20 text-fuchsia-400 border-fuchsia-500/30",
  "Slowcore": "bg-slate-600/20 text-slate-400 border-slate-600/30",
  "Emo": "bg-purple-700/20 text-purple-500 border-purple-700/30",
  "Comedy": "bg-yellow-300/20 text-yellow-200 border-yellow-300/30",
  "Novelty": "bg-yellow-300/20 text-yellow-200 border-yellow-300/30",
  "Glam Rock": "bg-pink-700/20 text-pink-500 border-pink-700/30",
  "Psychedelic Rock": "bg-purple-500/20 text-purple-400 border-purple-500/30",
  "Orchestral": "bg-stone-500/20 text-stone-400 border-stone-500/30",
  "Folk Punk": "bg-lime-700/20 text-lime-500 border-lime-700/30",
  "Folk Metal": "bg-green-700/20 text-green-500 border-green-700/30",
  "Ethio-Jazz": "bg-yellow-700/20 text-yellow-500 border-yellow-700/30",
  "Highlife": "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  "Japanese": "bg-red-300/20 text-red-200 border-red-300/30",
  "South African": "bg-green-500/20 text-green-400 border-green-500/30",
  "Arabic Rock": "bg-amber-700/20 text-amber-500 border-amber-700/30",
  "Bollywood": "bg-orange-400/20 text-orange-300 border-orange-400/30",
  "French Pop": "bg-blue-300/20 text-blue-200 border-blue-300/30",
  "Industrial Metal": "bg-zinc-700/20 text-zinc-500 border-zinc-700/30",
  "Alternative Metal": "bg-zinc-600/20 text-zinc-400 border-zinc-600/30",
  "Hardcore Punk": "bg-red-900/20 text-red-600 border-red-900/30",
  "Post-Hardcore": "bg-red-700/20 text-red-500 border-red-700/30",
  "Rap Metal": "bg-orange-800/20 text-orange-600 border-orange-800/30",
  "Nu Metal": "bg-zinc-500/20 text-zinc-400 border-zinc-500/30",
  "Gothic Rock": "bg-slate-800/20 text-slate-500 border-slate-800/30",
  "Other": "bg-gray-500/20 text-gray-400 border-gray-500/30",
};

export function getGenreColor(genre: string): string {
  return genreColors[genre] || genreColors["Other"];
}
